spring:

  # db setting
#  datasource:
#    url: jdbc:postgresql://localhost:5432/testdb
#    driver-class-name: org.postgresql.Driver
#    username: root
#    password: 1234


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.bootmybatisbase
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # Logging set


# db cluster setting
custom:
  datasource:
    master:
      jdbc-url: jdbc:postgresql://192.168.219.171:5433/postgres
      driver-class-name: org.postgresql.Driver
      username: miro
      password: miroit0621!
    slave:
      jdbc-url: jdbc:postgresql://192.168.219.171:5433/postgres
      driver-class-name: org.postgresql.Driver
      username: miro
      password: miroit0621!


# query logging setting
logging:
  level:
    root: INFO
    org.mybatis: DEBUG
    org.mybatis.spring: DEBUG
    com.bootmybatisbase: DEBUG
    com.zaxxer.hikari.HikariDataSource: DEBUG
    com.p6spy: WARN


# swagger setting
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha # 알파벳 순서로 정렬
    operations-sorter: method # 메소드 순서로 정렬
    doc-expansion: none # 카테고리가 접힌상태로 로딩
    persist-authorization: true # 브라우저를 새로고침 하더라도 인증정보 유지
  packages-to-scan: com.bootmybatisbase
  title: boot-mybatis-base API 문서 (dev)
  version: 1.0.0


# jwt setting
jwt:
  issuer: bootmybatisbase
  access-token-secret-key: bootmybatisbase_access_secret_bootmybatisbase_access_secret
  access-token-expiration: 3600000 # 1시간
  refresh-token-secret-key: bootmybatisbase_refresh_secret_bootmybatisbase_refresh_secret
  refresh-token-expiration: 2592000000 # 1개월


# file
bootmybatisbase:
  file:
    upload:
      root-path: tmp/files/uploads
      file-max-size: 10485760 # 10MB (10 * 1024 * 1024)